# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('host_area', models.CharField(max_length=255)),
                ('host_address', models.TextField(max_length=1001)),
                ('host_image', models.ImageField(max_length=255, upload_to='rockworthy/static/assets/event_hosts/main_photo')),
                ('host_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Event Hosts',
                'verbose_name': 'Event Host',
            },
        ),
    ]
