# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockworthy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='event_type',
            field=models.CharField(choices=[('Live Shows', 'Live Shows'), ('Art Exhibition', 'Art Exhibition')], default='Live Shows', max_length=14),
        ),
    ]
