# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockworthy', '0002_eventhost_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='host_type',
            field=models.CharField(choices=[('Special Event', 'Special Event'), ('Venue', 'Venue')], default='Venue', max_length=13),
        ),
    ]
